[pytest]
testpaths = tests
pythonpath = .
addopts = -q -s
markers =
    small: Tests running within a single process
    medium: A test that permits the use of external resources within a closed environment on a single machine
    large: Tests that allow network access to remote machines from automated tests
